sylius_resource:
    resources:
        mangoweb_labels_plugin.label:
            driver: doctrine/orm
            classes:
                model: MangoSylius\LabelsPlugin\Entity\Label
                form: MangoSylius\LabelsPlugin\Form\Type\LabelType
                repository: MangoSylius\LabelsPlugin\Repository\LabelRepository

sylius_grid:
    grids:
        mangoweb_labels_plugin_label:
            driver:
                name: doctrine/orm
                options:
                    class: "%mangoweb_labels_plugin.model.label.class%"
            fields:
                color:
                    type: twig
                    label: mango-sylius.admin.label.color
                    options:
                        template: "@MangoSyliusLabelsPlugin/Admin/Label/Grid/Field/color.html.twig"
                name:
                    type: string
                    label: mango-sylius.admin.label.name
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
        sylius_admin_order:
            fields:
                labels:
                    type: twig
                    path: .
                    label: mangoweb_labels_plugin.ui.labels
                    options:
                        template: "@MangoSyliusLabelsPlugin/Admin/Order/Grid/labels.html.twig"
