services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: false

    MangoSylius\LabelsPlugin\Menu\AdminMenuListener:
        tags:
            - name: kernel.event_listener
              event: sylius.menu.admin.main
              method: addAdminMenuItems

    MangoSylius\LabelsPlugin\Form\Type\LabelType:
        tags:
            - name: form.type
        arguments:
            - '%mangoweb_labels_plugin.model.label.class%'
            - ['sylius']

    mango-sylius.block_event_listener.admin.layout.javascripts:
        class: Sylius\Bundle\UiBundle\Block\BlockEventListener
        arguments:
            - '@@MangoSyliusLabelsPlugin/Admin/_javascripts.html.twig'
        tags:
            - { name: kernel.event_listener, event: sonata.block.event.sylius.admin.layout.javascripts, method: onBlockEvent }

    MangoSylius\LabelsPlugin\Service\LabelService:
        arguments:
            $labelRepository: '@mangoweb_labels_plugin.repository.label'

    MangoSylius\LabelsPlugin\Controller\AjaxLabelsController:
        public: true
        arguments:
            $eventDispatcher: '@event_dispatcher'
            $labelRepository: '@mangoweb_labels_plugin.repository.label'
            $entityManager: '@doctrine.orm.default_entity_manager'
            $orderRepository: '@sylius.repository.order'

    MangoSylius\LabelsPlugin\Twig\LabelsExtension:
        tags:
            - { name: twig.extension }
        arguments:
            $labelService: '@MangoSylius\LabelsPlugin\Service\LabelService'
